# Pythonの公式イメージをベースに使用
FROM python:3.9-slim

# 作業ディレクトリを設定
WORKDIR /app

# 依存ライブラリをインストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# アプリケーションコードをコピー
COPY ./main.py ./
COPY ./models.py ./

# FastAPIが使用するポート8000番を公開
EXPOSE 8000

# アプリケーションを起動
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]