FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app_streamlit.py ./

# Streamlitが使用するポート8501番を公開
EXPOSE 8501

# アプリケーションを起動
CMD ["streamlit", "run", "app_streamlit.py"]